/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientsVendorsRouteImport } from './routes/clients-vendors'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioProjectIdRouteImport } from './routes/portfolio.$projectId'
import { Route as PortfolioNewRouteImport } from './routes/portfolio.new'
import { Route as PortfolioProjectIdEditRouteImport } from './routes/portfolio.$projectId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsVendorsRoute = ClientsVendorsRouteImport.update({
  id: '/clients-vendors',
  path: '/clients-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectIdRoute = PortfolioProjectIdRouteImport.update({
  id: '/portfolio/$projectId',
  path: '/portfolio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioNewRoute = PortfolioNewRouteImport.update({
  id: '/portfolio/new',
  path: '/portfolio/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectIdEditRoute = PortfolioProjectIdEditRouteImport.update({
  id: '/portfolio/$projectId_/edit',
  path: '/portfolio/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/clients-vendors': typeof ClientsVendorsRoute
  '/financials': typeof FinancialsRoute
  '/organization': typeof OrganizationRoute
  '/resources': typeof ResourcesRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portfolio/$projectId/edit': typeof PortfolioProjectIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/clients-vendors': typeof ClientsVendorsRoute
  '/financials': typeof FinancialsRoute
  '/organization': typeof OrganizationRoute
  '/resources': typeof ResourcesRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/portfolio/$projectId/edit': typeof PortfolioProjectIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/clients-vendors': typeof ClientsVendorsRoute
  '/financials': typeof FinancialsRoute
  '/organization': typeof OrganizationRoute
  '/resources': typeof ResourcesRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portfolio/$projectId_/edit': typeof PortfolioProjectIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/auth'
    | '/clients-vendors'
    | '/financials'
    | '/organization'
    | '/resources'
    | '/portfolio/$projectId'
    | '/portfolio/new'
    | '/portfolio/'
    | '/portfolio/$projectId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/auth'
    | '/clients-vendors'
    | '/financials'
    | '/organization'
    | '/resources'
    | '/portfolio/$projectId'
    | '/portfolio/new'
    | '/portfolio'
    | '/portfolio/$projectId/edit'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/auth'
    | '/clients-vendors'
    | '/financials'
    | '/organization'
    | '/resources'
    | '/portfolio/$projectId'
    | '/portfolio/new'
    | '/portfolio/'
    | '/portfolio/$projectId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuthRoute: typeof AuthRoute
  ClientsVendorsRoute: typeof ClientsVendorsRoute
  FinancialsRoute: typeof FinancialsRoute
  OrganizationRoute: typeof OrganizationRoute
  ResourcesRoute: typeof ResourcesRoute
  PortfolioProjectIdRoute: typeof PortfolioProjectIdRoute
  PortfolioNewRoute: typeof PortfolioNewRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PortfolioProjectIdEditRoute: typeof PortfolioProjectIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients-vendors': {
      id: '/clients-vendors'
      path: '/clients-vendors'
      fullPath: '/clients-vendors'
      preLoaderRoute: typeof ClientsVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$projectId': {
      id: '/portfolio/$projectId'
      path: '/portfolio/$projectId'
      fullPath: '/portfolio/$projectId'
      preLoaderRoute: typeof PortfolioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/new': {
      id: '/portfolio/new'
      path: '/portfolio/new'
      fullPath: '/portfolio/new'
      preLoaderRoute: typeof PortfolioNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$projectId_/edit': {
      id: '/portfolio/$projectId_/edit'
      path: '/portfolio/$projectId/edit'
      fullPath: '/portfolio/$projectId/edit'
      preLoaderRoute: typeof PortfolioProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuthRoute: AuthRoute,
  ClientsVendorsRoute: ClientsVendorsRoute,
  FinancialsRoute: FinancialsRoute,
  OrganizationRoute: OrganizationRoute,
  ResourcesRoute: ResourcesRoute,
  PortfolioProjectIdRoute: PortfolioProjectIdRoute,
  PortfolioNewRoute: PortfolioNewRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PortfolioProjectIdEditRoute: PortfolioProjectIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
